import { StyleSheet } from "react-native";
import { AppColors } from "@/src/shared/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  headerBtn: { paddingHorizontal: 12, paddingVertical: 6 },
  headerBtnText: { color: "#fff", fontSize: 14, fontWeight: "500" },
  saveBtn: {
    backgroundColor: AppColors.primary,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
  },
  saveBtnText: { color: "#fff", fontSize: 14, fontWeight: "bold" },
  loaderContainer: {
    height: 64,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  mainContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  imageCard: {
    width: "100%",
    height: "80%",
    backgroundColor: "#111",
    borderRadius: 12,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  mainImage: { width: "100%", height: "100%" },
  deleteBtn: {
    position: "absolute",
    top: 15,
    left: 15,
    width: 32,
    height: 32,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  pageNavRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 25,
    marginTop: 15,
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
  },
  navArrow: { padding: 5 },
  pageNumberText: { color: "white", fontSize: 14, fontWeight: "600" },
  bottomBar: {
    backgroundColor: "#111",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingBottom: 10,
  },
  tabContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 15,
    gap: 25,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  tabItem: {
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  activeTab: { borderBottomColor: AppColors.primary },
  tabText: { color: "#666", fontSize: 14, fontWeight: "600" },
  activeTabText: { color: AppColors.primary },
  toolsContainer: { paddingVertical: 10 },
  toolsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 10,
    gap: 5,
  },
  toolItem: { alignItems: "center", width: 72, height: 60, gap: 4 },
  toolLabel: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 14,
  },
  subToolRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    gap: 15,
  },
  subToolLabel: { color: "#9ca3af", fontSize: 12, marginRight: 10 },
  subToolBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#333",
    borderRadius: 6,
  },
  subToolText: { color: "white", fontSize: 12 },
  cropInterface: { paddingBottom: 10 },
  cropToolBtn: { alignItems: "center", gap: 4, flex: 1 },
  cropToolLabel: { fontSize: 10, color: "#9ca3af" },
  ratioBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    gap: 10,
    marginTop: 10,
  },
  confirmRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: "#333",
    marginTop: 15,
  },
  confirmTitle: { fontSize: 16, fontWeight: "bold", color: "white" },
  cancelAction: { padding: 10 },
  confirmAction: { padding: 10 },
  compareRow: { marginBottom: 10 },
  compareBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
  },
  compareText: { fontSize: 12, color: "white", fontWeight: "600" },
  ocrOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  ocrText: { marginTop: 15, color: "white", fontSize: 16, fontWeight: "500" },
  editorModal: { flex: 1, backgroundColor: "#000" },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "white" },
  editorContent: { flex: 1, padding: 20 },
  textInput: {
    color: "white",
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: "top",
  },
  copyBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#333",
    margin: 20,
    padding: 15,
    borderRadius: 12,
    gap: 10,
  },
  copyBtnText: { color: "white", fontWeight: "600" },
  eraseInterface: { backgroundColor: "#111", paddingBottom: 10 },
  eraseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  undoBtn: { padding: 8, opacity: 0.5 },
  pageIndicatorContainer: {
    backgroundColor: "#222",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  pageIndicatorText: { color: "white", fontSize: 12, fontWeight: "600" },
  compareBtnSmall: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#333",
  },
  compareBtnTextSmall: { color: "#9ca3af", fontSize: 12 },
  toolsScrollContainer: {
    height: 100,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  eraseToolsScroll: { paddingHorizontal: 15, alignItems: "center", gap: 10 },
  eraseToolItem: {
    alignItems: "center",
    minWidth: 80,
    gap: 8,
    paddingVertical: 10,
  },
  activeEraseTool: {
    borderBottomWidth: 2,
    borderBottomColor: AppColors.primary,
  },
  eraseIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#222",
    justifyContent: "center",
    alignItems: "center",
  },
  activeEraseIconContainer: { backgroundColor: AppColors.primary },
  eraseToolLabel: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "500",
    textAlign: "center",
  },
  activeEraseToolLabel: { color: "white" },
  eraseFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
});
