import { StyleSheet } from "react-native";
import { AppColors } from "@/src/shared/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppColors.dark.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 15,
    gap: 15,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: AppColors.dark.surface,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    color: AppColors.dark.textPrimary,
    fontSize: 15,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  premiumBtn: { borderRadius: 20, overflow: "hidden" },
  premiumGradient: {
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  profileCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: AppColors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.1)",
  },
  profileInitial: { color: "white", fontWeight: "bold", fontSize: 16 },
  scrollContent: { paddingBottom: 100 },
  heroSection: { paddingHorizontal: 20, paddingVertical: 15 },
  heroTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    fontSize: 14,
    color: AppColors.dark.textHint,
    marginTop: 4,
    fontWeight: "500",
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    marginTop: 10,
  },
  gridItem: { width: "25%", alignItems: "center", paddingVertical: 15, gap: 8 },
  iconCircle: {
    width: 56,
    height: 56,
    borderRadius: 20,
    backgroundColor: AppColors.dark.surface,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  gridLabel: {
    fontSize: 11,
    color: "#cbd5e1",
    fontWeight: "600",
    textAlign: "center",
  },
  badge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#ef4444",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  badgeText: { color: "white", fontSize: 9, fontWeight: "bold" },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 25,
    marginBottom: 15,
  },
  sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#fff" },
  viewAllBtn: { flexDirection: "row", alignItems: "center", gap: 4 },
  viewAll: { fontSize: 13, color: AppColors.primary, fontWeight: "600" },
  docItemWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  docListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  docThumbnailSquare: {
    width: 54,
    height: 54,
    backgroundColor: "#333",
    borderRadius: 4,
    overflow: "hidden",
  },
  thumbnailImg: { width: "100%", height: "100%" },
  docInfo: { flex: 1, marginLeft: 15 },
  docTitleList: {
    fontSize: 16,
    color: "#eee",
    fontWeight: "500",
    marginBottom: 4,
  },
  docMetaRow: { flexDirection: "row", alignItems: "center" },
  docMetaText: { fontSize: 12, color: AppColors.dark.textHint },
  metaDivider: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: AppColors.dark.textHint,
    marginHorizontal: 8,
  },
  selectionCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  fab: {
    position: "absolute",
    bottom: 30,
    right: 20,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: AppColors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    shadowColor: AppColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#1c1c1e",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#fff" },
  optionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  optionText: { marginLeft: 15, fontSize: 16, color: "#eee" },
  renameContainer: { padding: 20 },
  renameInput: {
    backgroundColor: "#2c2c2e",
    borderRadius: 10,
    padding: 15,
    color: "#fff",
    fontSize: 16,
    marginBottom: 20,
  },
  renameButtons: { flexDirection: "row", gap: 10 },
  renameBtn: { flex: 1, padding: 15, borderRadius: 10, alignItems: "center" },
  cancelBtn: { backgroundColor: "#3a3a3c" },
  confirmBtn: { backgroundColor: AppColors.primary },
  renameBtnText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  docIconPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#222",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderCharSmall: { color: "white", fontWeight: "bold" },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 100,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 20,
  },
  emptyText: {
    color: AppColors.dark.textHint,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
  },
});
