import { StyleSheet, Dimensions } from "react-native";
import { AppColors } from "@/src/shared/constants/theme";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  camera: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
    justifyContent: "space-between",
  },
  topControlWrapper: {
    backgroundColor: "black",
  },
  cameraOverlay: {
    flex: 1,
    justifyContent: "space-between",
    backgroundColor: "transparent",
  },
  hdBadgeHeader: {
    borderWidth: 1.5,
    borderColor: "white",
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  hdBadgeHeaderActive: {
    borderColor: "#10b981",
  },
  hdBadgeHeaderText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  hdBadgeHeaderTextActive: {
    color: "#10b981",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#000",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 5,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  iconBtn: {
    padding: 10,
  },
  gridContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  gridBox: {
    borderWidth: 0, // Remove fixed border
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  corner: {
    position: "absolute",
    width: 30,
    height: 30,
    borderColor: "#10b981",
  },
  topLeft: { top: -2, left: -2, borderTopWidth: 4, borderLeftWidth: 4 },
  topRight: { top: -2, right: -2, borderTopWidth: 4, borderRightWidth: 4 },
  bottomLeft: {
    bottom: -2,
    left: -2,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
  },
  bottomRight: {
    bottom: -2,
    right: -2,
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  scanLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: "#10b981",
  },
  laserGradient: {
    height: 40,
    width: "100%",
    marginTop: -20,
  },
  hintText: {
    color: "white",
    marginTop: 20,
    fontSize: 13,
    fontWeight: "500",
    opacity: 0.8,
  },
  batchToggle: {
    flexDirection: "row",
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 20,
    padding: 4,
    marginTop: 20,
  },
  batchBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 18,
  },
  activeBatchBtn: {
    backgroundColor: "#444",
  },
  batchText: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "600",
  },
  activeBatchText: {
    color: "white",
  },
  footer: {
    paddingBottom: 15,
    backgroundColor: "rgba(0,0,0,0.8)",
  },
  modeTabsWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.05)",
  },
  modeTabs: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    gap: 15, // Reduced gap for better snapping
  },
  modeTab: {
    alignItems: "center",
    position: "relative",
  },
  activeModeTab: {},
  modeText: {
    color: "#9ca3af",
    fontSize: 13,
    fontWeight: "600",
  },
  activeModeText: {
    color: "#10b981",
  },
  modeDot: {
    position: "absolute",
    top: -4,
    right: -6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#ef4444",
  },
  mainControls: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingTop: 10,
    paddingHorizontal: 10,
  },
  controlItem: {
    alignItems: "center",
    gap: 8,
    width: 80,
  },
  controlLabel: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  captureBtn: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: "#10b981",
    justifyContent: "center",
    alignItems: "center",
  },
  captureBtnInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  finishBadge: {
    position: "relative",
  },
  countBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#ef4444",
    width: 18,
    height: 18,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "white",
  },
  countBadgeText: {
    color: "white",
    fontSize: 9,
    fontWeight: "bold",
  },
  permissionBtn: {
    backgroundColor: AppColors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  flashMenu: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "rgba(0,0,0,0.85)",
    paddingVertical: 15,
    zIndex: 200,
  },
  flashOption: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 6,
  },
  activeFlashOption: {
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  flashOptionText: {
    color: "#9ca3af",
    fontSize: 13,
    fontWeight: "600",
  },
  activeFlashText: {
    color: "#10b981",
  },
  hdMenu: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "rgba(0,0,0,0.85)",
    paddingVertical: 15,
    zIndex: 200,
    alignItems: "center",
  },
  hdOption: {
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  activeHdOption: {
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  hdLabel: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
  hdSubLabel: {
    color: "#9ca3af",
    fontSize: 10,
    marginTop: 2,
  },
  activeHdText: {
    color: "#10b981",
  },
  capturedThumbnail: {
    width: 45,
    height: 45,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "white",
    overflow: "hidden",
    position: "relative",
    backgroundColor: "#333",
  },
  thumbImage: {
    width: "100%",
    height: "100%",
  },
  thumbBadge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#10b981",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: "#000",
  },
  thumbBadgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  settingsOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  settingsModal: {
    width: width * 0.85,
    backgroundColor: "#1a1a1a",
    borderRadius: 20,
    padding: 20,
    position: "relative",
  },
  settingsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  settingsTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  settingsTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  settingInfo: {
    flex: 1,
  },
  settingLabel: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
  },
  settingValue: {
    color: "#10b981",
    fontSize: 12,
    marginTop: 2,
  },
  settingActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  moreSettingsBtn: {
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
  },
  moreSettingsText: {
    color: "#10b981",
    fontSize: 15,
    fontWeight: "600",
  },
  batchToggleOutside: {
    flexDirection: "row",
    backgroundColor: "#1f2937",
    borderRadius: 20,
    padding: 4,
    alignSelf: "center",
    marginVertical: 10,
    zIndex: 5,
  },
  activeTabIndicator: {
    position: "absolute",
    top: -10,
    width: 20,
    height: 3,
    backgroundColor: "#10b981",
    borderRadius: 2,
  },
  batchThumbContainer: {
    position: "absolute",
    right: 20,
    top: -90,
    alignItems: "center",
    zIndex: 10,
  },
  thumbWrapper: {
    width: 54,
    height: 54,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "white",
    overflow: "hidden",
    backgroundColor: "#333",
  },
  batchThumb: {
    width: "100%",
    height: "100%",
  },
  batchBadge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#ef4444",
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
    zIndex: 20,
    paddingHorizontal: 4,
  },
  batchBadgeText: {
    color: "white",
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
    includeFontPadding: false,
    textAlignVertical: "center",
    lineHeight: 14, // Override the default 24 to allow centering
  },
  ubahBtn: {
    backgroundColor: "#10b981",
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
  },
  ubahText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  thumbArrow: {
    position: "absolute",
    right: -15,
    top: 18,
  },
  selesaiBtn: {
    backgroundColor: "#10b981",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  selesaiText: {
    color: "white",
    fontSize: 14,
    fontWeight: "bold",
  },
});
